name: renovate-config

on:
  push:
    paths:
      - '.github/renovate.json5'
    branches:
      - main
      - 'releases-**'
  pull_request:
    paths:
      - '.github/renovate.json5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      - run: npx --package renovate -c 'renovate-config-validator'
